// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuO5PYxGcfhapQPMoZdCWxJ7qRzJ5EHIw',
    appId: '1:371978764008:web:6262ae094bb47edd2d135d',
    messagingSenderId: '371978764008',
    projectId: 'dup-a79d6',
    authDomain: 'dup-a79d6.firebaseapp.com',
    storageBucket: 'dup-a79d6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA99uhwznMM-SqclES4kddV7gyWdVaHqlo',
    appId: '1:371978764008:android:d0fa3c5df01f06362d135d',
    messagingSenderId: '371978764008',
    projectId: 'dup-a79d6',
    storageBucket: 'dup-a79d6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDftMmflp3BQkn4dO3qd81qdiYIa6XhRs8',
    appId: '1:371978764008:ios:e99c59ac172c86502d135d',
    messagingSenderId: '371978764008',
    projectId: 'dup-a79d6',
    storageBucket: 'dup-a79d6.firebasestorage.app',
    iosBundleId: 'com.duco.dup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDftMmflp3BQkn4dO3qd81qdiYIa6XhRs8',
    appId: '1:371978764008:ios:e99c59ac172c86502d135d',
    messagingSenderId: '371978764008',
    projectId: 'dup-a79d6',
    storageBucket: 'dup-a79d6.firebasestorage.app',
    iosBundleId: 'com.duco.dup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuO5PYxGcfhapQPMoZdCWxJ7qRzJ5EHIw',
    appId: '1:371978764008:web:afc8d8388114c9e82d135d',
    messagingSenderId: '371978764008',
    projectId: 'dup-a79d6',
    authDomain: 'dup-a79d6.firebaseapp.com',
    storageBucket: 'dup-a79d6.firebasestorage.app',
  );
}
