import 'package:cloud_firestore/cloud_firestore.dart';

class Worker {
  String uid; // Unique Worker ID (Generated by Firestore)
  String workerName;
  String jobTitle;
  String description;
  String phone;
  String city;
  Timestamp? timestamp; // Stores Firestore server timestamp

  Worker({
    required this.uid,
    required this.workerName,
    required this.jobTitle,
    required this.description,
    required this.phone,
    required this.city,
    this.timestamp,
  });

  // Convert Worker object to Map (for Firestore)
  Map<String, dynamic> toMap() {
    return {
      'uid': uid,
      'workerName': workerName,
      'jobTitle': jobTitle,
      'description': description,
      'phone': phone,
      'city': city,
      'timestamp': timestamp ?? FieldValue.serverTimestamp(), // Auto timestamp
    };
  }

  // Create Worker object from Firestore document
  factory Worker.fromMap(Map<String, dynamic> map) {
    return Worker(
      uid: map['uid'], //,
      workerName: map['workerName'] ?? '',
      jobTitle: map['jobTitle'] ?? '',
      description: map['description'] ?? '',
      phone: map['phone'] ?? '',
      city: map['city'] ?? '',
      timestamp: map['timestamp'], // Firestore stores Timestamp, not DateTime
    );
  }
}
